### ISSUE TITLE
The generated apk missing lib armeabi_v7a

### ISSUE THREAD

**Issue by a365344743s** [LuigiVampa92/xapk-to-apk#3]
source xapk:
[AppLock Plus - App Lock & Safe_1.4.0_apkcombo.com.xapk.zip](https://github.com/LuigiVampa92/xapk-to-apk/files/15019984/AppLock.Plus.-.App.Lock.Safe_1.4.0_apkcombo.com.xapk.zip)
generated apk:
[AppLock Plus - App Lock & Safe_1.4.0_apkcombo.com.apk.zip](https://github.com/LuigiVampa92/xapk-to-apk/files/15019986/AppLock.Plus.-.App.Lock.Safe_1.4.0_apkcombo.com.apk.zip)

The xapk contain lib armeabi_v7a, but the generated apk missing lib armeabi_v7a.

**Comment by LuigiVampa92** [comment]
Hi, thanks for the interest to the project!

Yes, I have truly missed the armeabi_v7a architecture name. Probably thought that I compare the strings with "startswith()" and not by strict equality. Some really old applications have old "armeabi" name without the suffix. Fixed that now.

Thanks again for your attentiveness!
